// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJRaA4B5nO25ZgFKFEDsPiIZDUTUUskco',
    appId: '1:381488569563:web:7e5bc96adb801ec1e9c0fe',
    messagingSenderId: '381488569563',
    projectId: 'womansafetyapplication-f1f16',
    authDomain: 'womansafetyapplication-f1f16.firebaseapp.com',
    storageBucket: 'womansafetyapplication-f1f16.appspot.com',
    measurementId: 'G-GC6N8W2Y44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFqYd4c8o06IZX_uVUG5XeCfCjbfX43_Q',
    appId: '1:381488569563:android:0d3e931cc692760be9c0fe',
    messagingSenderId: '381488569563',
    projectId: 'womansafetyapplication-f1f16',
    storageBucket: 'womansafetyapplication-f1f16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX0UDPvToPdPX4zW_3n6xc69i_bGt96Rg',
    appId: '1:381488569563:ios:c315291ba47d8538e9c0fe',
    messagingSenderId: '381488569563',
    projectId: 'womansafetyapplication-f1f16',
    storageBucket: 'womansafetyapplication-f1f16.appspot.com',
    iosBundleId: 'com.example.womansafety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX0UDPvToPdPX4zW_3n6xc69i_bGt96Rg',
    appId: '1:381488569563:ios:c315291ba47d8538e9c0fe',
    messagingSenderId: '381488569563',
    projectId: 'womansafetyapplication-f1f16',
    storageBucket: 'womansafetyapplication-f1f16.appspot.com',
    iosBundleId: 'com.example.womansafety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJRaA4B5nO25ZgFKFEDsPiIZDUTUUskco',
    appId: '1:381488569563:web:b02d7a00721e95b5e9c0fe',
    messagingSenderId: '381488569563',
    projectId: 'womansafetyapplication-f1f16',
    authDomain: 'womansafetyapplication-f1f16.firebaseapp.com',
    storageBucket: 'womansafetyapplication-f1f16.appspot.com',
    measurementId: 'G-7X31JGMVN4',
  );
}
